services:
  wiremock-api:
    image: wiremock/wiremock:3.13.2-2
    container_name: wiremock-api
    ports:
      - "18081:8080"
    command:
      - "--global-response-templating"
      - "--verbose"
    volumes:
      - ./mock/wiremock:/home/wiremock
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/__admin"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
